import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

-- ============================================================================
-- Ideals and Kernels
-- ============================================================================
--
-- Ideals are to rings what normal subgroups are to groups:
--   - Normal subgroup N ◁ G  ⟹  quotient group  G/N
--   - Ideal         I ⊆ R   ⟹  quotient ring   R/I

-- ============================================================================
-- Section 1: What is an ideal?
-- ============================================================================
--
-- An ideal I ⊆ R is a subset that is:
--   1. An additive subgroup:    0 ∈ I,  a, b ∈ I ⟹ a - b ∈ I
--   2. Closed under multiplication BY ANYTHING in R (the absorbing property):
--      a ∈ I, r ∈ R  ⟹  r * a ∈ I
--
-- The absorbing property is the key one — it's what distinguishes an ideal
-- from a subring. The canonical example: multiples of n in ℤ.

-- The set of multiples of 3 in ℤ, written (3) or 3ℤ:
example : Ideal ℤ := Ideal.span {3}

-- 6 ∈ (3), -9 ∈ (3), 7 ∉ (3)
example : (6 : ℤ) ∈ Ideal.span ({3} : Set ℤ) := by
  rw [Ideal.mem_span_singleton]; exact ⟨2, by ring⟩

example : (-9 : ℤ) ∈ Ideal.span ({3} : Set ℤ) := by
  rw [Ideal.mem_span_singleton]; exact ⟨-3, by ring⟩

example : (7 : ℤ) ∉ Ideal.span ({3} : Set ℤ) := by
  rw [Ideal.mem_span_singleton]; decide

-- ============================================================================
-- Section 2: The inclusion order — "bigger" means "denser"
-- ============================================================================
--
-- Ideals are ordered by ⊆. In ℤ every ideal is countably infinite, so
-- "bigger" can't mean "more elements." The right intuition is DENSITY:
--
--   ℤ = (1):    ●●●●●●●●●●●●●●●●●●●●●●●●●●●  (every integer)
--   (2):        ●·●·●·●·●·●·●·●·●·●·●·●·●·●  (every 2nd)
--   (3):        ●··●··●··●··●··●··●··●··●··  (every 3rd)
--   (6):        ●·····●·····●·····●·····●··  (every 6th)
--   (12):       ●···········●···········●··  (every 12th)
--
-- Asymptotic density of (n) is 1/n. Side effect: BIGGER generator
-- → SMALLER ideal. Every multiple of 6 is a multiple of 3, so (6) ⊆ (3).

example : Ideal.span ({6} : Set ℤ) ≤ Ideal.span ({3} : Set ℤ) := by
  rw [Ideal.span_singleton_le_span_singleton]
  exact ⟨2, by ring⟩

-- The two extremes:
example : Ideal ℤ := ⊥                                 -- {0}, sparsest
example : Ideal ℤ := ⊤                                 -- ℤ, densest
example : (0 : ℤ) ∈ (⊥ : Ideal ℤ) := Ideal.zero_mem _
example : (42 : ℤ) ∈ (⊤ : Ideal ℤ) := trivial

-- An ideal contains 1 iff it's the whole ring (since r = r·1 ∈ I forces
-- everything in). We'll generalize this in §4: any UNIT in I forces I = R.
example (I : Ideal ℤ) (h : (1 : ℤ) ∈ I) : I = ⊤ :=
  (Ideal.eq_top_iff_one I).mpr h

-- Algebraic mirror of density: quotient size.  |ℤ/(n)| = n.
-- Sparser ideal → bigger quotient (more cosets). The construction is in §6.
example : Fintype.card (ZMod 6) = 6 := by decide
example : Fintype.card (ZMod 2) = 2 := by decide

-- ============================================================================
-- Section 3: Principal ideals — generated by one element
-- ============================================================================
--
-- The ideal "generated by a" is the smallest (sparsest) ideal containing a.
-- It equals { r * a | r ∈ R }, written (a) or Ideal.span {a}.
--
-- An ideal generated by one element is PRINCIPAL. A ring where every ideal
-- is principal is a principal ideal domain (PID). ℤ and k[X] are PIDs; most rings
-- aren't (e.g. in k[X, Y] the ideal (X, Y) needs two generators).

-- The principal ideal (6) = {..., -12, -6, 0, 6, 12, 18, ...}.
example : Ideal ℤ := Ideal.span {6}

-- Members are of the form r·6 for some r ∈ ℤ.
example : (12 : ℤ) ∈ Ideal.span ({6} : Set ℤ) := by    -- 12 = 2·6
  rw [Ideal.mem_span_singleton]; exact ⟨2, by ring⟩
example : (-18 : ℤ) ∈ Ideal.span ({6} : Set ℤ) := by   -- -18 = (-3)·6
  rw [Ideal.mem_span_singleton]; exact ⟨-3, by ring⟩

-- And (6) really is the SMALLEST ideal containing 6:
-- any ideal I with 6 ∈ I must contain every multiple of 6, hence all of (6).
example (I : Ideal ℤ) (h : (6 : ℤ) ∈ I) : Ideal.span ({6} : Set ℤ) ≤ I :=
  Ideal.span_le.mpr (Set.singleton_subset_iff.mpr h)

-- Edge cases:
example : Ideal.span ({0} : Set ℤ) = ⊥ := by simp
example : Ideal.span ({1} : Set ℤ) = ⊤ := by simp

-- ============================================================================
-- Section 4: Units
-- ============================================================================
--
-- An element u ∈ R is a UNIT if it has a multiplicative inverse.
-- Equivalently: (u) = R, the principal ideal of u is the whole ring.
-- The set of units forms a group Rˣ under multiplication.
--
-- This generalizes "1 ∈ I ⟹ I = R" from §2: any unit in I forces I = R.

example : IsUnit (1 : ℤ) := isUnit_one
example : ¬ IsUnit (2 : ℤ) := by rw [Int.isUnit_iff]; decide
example (x : ℚ) (hx : x ≠ 0) : IsUnit x := hx.isUnit

example : Fintype.card (ZMod 5)ˣ = 4 := by decide   -- 𝔽₅ \ {0}
example : Fintype.card (ZMod 6)ˣ = 2 := by decide   -- {1, 5}, coprime to 6

-- The unit group of any FINITE FIELD is cyclic (deep theorem; see Cyclic.lean).
-- (ℤ/Nℤ)ˣ has order φ(N) — the group RSA lives in.
example : IsCyclic (ZMod 5)ˣ :=
  haveI : Fact (Nat.Prime 5) := ⟨by decide⟩
  inferInstance

-- ============================================================================
-- Section 5: Kernels
-- ============================================================================
--
-- For a ring hom φ : R → S, the KERNEL is { r ∈ R | φ(r) = 0 }.
--
-- Theorem: ker φ is always an ideal. Conversely, every ideal is the kernel
-- of some hom (the projection R → R/I from §6). So ideals = kernels.
--
-- Classic example: reduction mod n. φ : ℤ → ℤ/nℤ, ker φ = nℤ.

example : ℤ →+* ZMod 5 := Int.castRingHom (ZMod 5)
example : (Int.castRingHom (ZMod 5)) 5 = 0 := by decide
example : (Int.castRingHom (ZMod 5)) 10 = 0 := by decide
example : (Int.castRingHom (ZMod 5)) 7 = 2 := by decide   -- not in kernel
example : Ideal ℤ := RingHom.ker (Int.castRingHom (ZMod 5))

-- ============================================================================
-- Section 6: Quotient rings — the construction
-- ============================================================================
--
-- Given an ideal I ⊆ R, form R/I by declaring a ~ b ⟺ a - b ∈ I.
-- The cosets [a] = a + I form a new ring, and I literally becomes the new
-- zero: [a] = 0 ⟺ a ∈ I.
--
-- Examples:
--   ℤ / (5)               = 𝔽₅     (integers mod 5)
--   𝔽₂[X] / (X² + X + 1)  = GF(4)  (a finite field with 4 elements)
--   ℝ[X] / (X² + 1)       ≅ ℂ      (the complex numbers)

-- ============================================================================
-- Section 7: Maximal and prime ideals
-- ============================================================================
--
-- Which ideals give us FIELDS? The MAXIMAL ones.
--
-- M is maximal if M ≠ R and no ideal squeezes strictly between M and R.
-- Theorem: R/M is a field  ⟺  M is maximal.

-- ----------------------------------------------------------------------------
-- The inclusion lattice in ℤ
-- ----------------------------------------------------------------------------
--
-- Recall from §2: bigger generator → sparser ideal. So the lattice grows
-- denser going UP, and maximal ideals sit JUST BELOW ℤ:
--
--   ℤ = (1)
--        │
--       (2)    (3)    (5)    (7)    ...
--        │      │
--       (4)    (9)
--        │      │
--       (8)    (27)
--        ⋮     ⋮
--
-- In ℤ:  (n) is maximal  ⟺  n is prime.
--
-- So ℤ has INFINITELY MANY maximal ideals — one for every prime — and each
-- gives a different field quotient:
--   ℤ/(2) = 𝔽₂, ℤ/(3) = 𝔽₃, ℤ/(5) = 𝔽₅, ℤ/(7) = 𝔽₇, ...
--
-- (Rings with exactly one maximal ideal are called LOCAL rings; ℤ isn't one.)
--
-- BY CONTRAST: a FIELD has only TWO ideals — {0} and itself — because every
-- nonzero element is a unit, and units force I = R (§4). Trivial lattice.
-- That's why ring theory cares about non-fields like ℤ and k[X]: they have
-- the RICH ideal structure to quotient by, and those quotients are often
-- where new fields come from (𝔽ₚ, GF(9), ℂ).

example : (Ideal.span ({5} : Set ℤ)).IsMaximal :=
  PrincipalIdealRing.isMaximal_of_irreducible <|
    (Int.prime_iff_natAbs_prime.mpr (by decide)).irreducible

example : (Ideal.span ({7} : Set ℤ)).IsMaximal :=
  PrincipalIdealRing.isMaximal_of_irreducible <|
    (Int.prime_iff_natAbs_prime.mpr (by decide)).irreducible

-- And so ℤ/(5) is a field (Mathlib derives the Field instance automatically):
noncomputable example : Field (ℤ ⧸ Ideal.span ({5} : Set ℤ)) :=
  haveI : (Ideal.span ({5} : Set ℤ)).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible <|
      (Int.prime_iff_natAbs_prime.mpr (by decide)).irreducible
  Ideal.Quotient.field _

-- Why "maximal ⟹ field": take nonzero [a] ∈ R/M, so a ∉ M. Then M + (a)
-- strictly contains M, so by maximality M + (a) = R. Hence 1 = m + r·a, and
-- mod M this gives [r][a] = 1. So [a] is invertible (Bézout in disguise.)

-- ----------------------------------------------------------------------------
-- The cousin: prime ideals
-- ----------------------------------------------------------------------------
--
-- P is PRIME if P ≠ R and  a·b ∈ P ⟹ a ∈ P or b ∈ P.
-- Theorem: R/P is an integral domain  ⟺  P is prime.
--
-- Every maximal ideal is prime, but not vice versa. Classic: in ℤ[X], (X)
-- is prime (quotient ≅ ℤ, a domain) but not maximal. (X, 5) is maximal,
-- with quotient ≅ 𝔽₅.
--
-- The hierarchy:
--
--   maximal ideal  ⟹  prime ideal  ⟹  proper ideal
--      │                  │                │
--      ▼                  ▼                ▼
--      field          integral domain     ring
--      (R/M)             (R/P)            (R/I)
